apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  # Adjust the storage size based on your needs
  storageClassName: gp2  # Ensure you're using gp2 storage class

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      #     serviceAccountName: jenkins-sa
      securityContext:
        fsGroup: 1000
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
        - name: jenkins-data
          mountPath: /var/jenkins_home
      - name: kubectl
        image: bitnami/kubectl:latest
        command: ["sleep", "infinity"]
      volumes:
      - name: jenkins-data
        persistentVolumeClaim:
          claimName: jenkins-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  ports:
  - name: http  # Name for the Jenkins UI port
    port: 8080
    targetPort: 8080
    nodePort: 32000  # Optional NodePort for Jenkins UI
  - name: agent  # Name for the Jenkins agent port
    port: 50000
    targetPort: 50000
    nodePort: 32001  # Optional NodePort for Jenkins agent
  selector:
    app: jenkins
  type: NodePort

